### PR TITLE
Fixed failing on unknown entities

### LINKED ISSUE #23: Incorrect/missing exception caught
https://github.com/iltar/http-bundle/blob/master/src/DoctrineBridge/EntityIdDescriptor.php#L62-L66

This exception should be catching the `Doctrine\Common\Persistence\Mapping` as well, which is not done. if you pass an unmanaged object, it might throw that exception in weird scenarios.

Suggestion: catch _all_ exceptions.

### PR DESCRIPTION
**Pull request by iltar**
Fixes #23. 

 - By catching more exceptions, the isManaged is more robust.
 - If an unresolvable value is passed to the generator, or it resolves
   to an empty string, it will now fail with a proper exception message.

These fixes solve some DX issues regarding error messages that are unclear as well, though eventually Symfony should probably fix these errors.

### CODE REVIEW

**Comment by yannickl88** [comment]
:+1:

File: src/Exception/UnresolvedParameterException.php [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+/**
+ * @author Iltar van der Berg <kjarli@gmail.com>
+ */
+class UnresolvedParameterException extends \RuntimeException
+{
+    private $parameters;
+
+    public function __construct(array $parameters)
+    {
+        parent::__construct(sprintf('Unable to resolve parameters for the following route arguments: %s.', implode(', ', array_keys($parameters))));
```
Comment (wouterj) [inline src/Exception/UnresolvedParameterException.php]: arguments -> parameters ?

File: src/Router/ParameterResolvingRouter.php [hunk 2]
```diff
@@ -63,6 +64,27 @@ public function getRouteCollection()
...
+
+        foreach ($resolvedParameters as $key => $parameter) {
+            // sanity check for parameters that could not be resolved at all
+            if (is_object($parameter)) {
+                $unresolved[$key] = get_class($parameter);
+                continue;
+            }
+
+            // sanity check for parameters that could not be resolved into a usable value
+            if ('' === (string) $parameter) {
```
Comment (wouterj) [inline src/Router/ParameterResolvingRouter.php]: Isn't this a bit scary (i.e. an array variable would result in an notice here?)

Comment (iltar) [inline src/Router/ParameterResolvingRouter.php]: Arrays aren't allowed in the first place, they would've caused an issue in the generate method already. I could add an array check as well. I think that should cover most cases :thinking:

File: src/Exception/UnresolvedParameterException.php (hunk 1 above)
Comment (iltar) [inline src/Exception/UnresolvedParameterException.php]: Indeed :+1:

**Comment by greg0ire** [comment]
In your commit message: "rebust" => "robust"

**Comment by iltar** [comment]
@greg0ire thanks, I will grab some more coffee before I continue :smile: 
@wouterj I've adapted the code to always try and resolve it to a scalar value (which can be cast to a string), wdyt?

File: src/Router/ParameterResolvingRouter.php (hunk 2 above)
Comment (yannickl88) [inline src/Router/ParameterResolvingRouter.php]: https://3v4l.org/Ku6mM
